// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htqkdxoulmmnnauuzbnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0cWtkeG91bG1tbm5hdXV6Ym5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTUzMTYsImV4cCI6MjA2NjYzMTMxNn0.5sBjKNdYfU8tnHau3bgbWNADjPSo80CIzOkutqV5AjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);